print('Pick 3 numbers')
a = input('Pick the first number: ')
b = input('Pick the second number: ')
c = input('Pick the third number: ')

a = float(a)
b = float(b)
c = float(c)
p = min(a, b , c)
print(p)
